spring:
  application:
    name: kafka-proto-publisher
server:
  port: 9000
kafka:
  config:
    boot-strap-server: "127.0.0.1:9092"
    value-deserializer: "io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer"
    schema-registry-url: "http://127.0.0.1:8081"
    topic-user:
      group-id: "topic.user.message.groupId"
      topic: "topic.user.message"
